# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "nvme/rpool/rootfs";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "nvme/rpool/local/nix";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "nvme/rpool/rootfs/home";
      fsType = "zfs";
    };

  fileSystems."/root" =
    { device = "nvme/rpool/rootfs/root";
      fsType = "zfs";
    };

  fileSystems."/tmp" =
    { device = "nvme/rpool/rootfs/tmp";
      fsType = "zfs";
    };

  fileSystems."/var" =
    { device = "nvme/rpool/rootfs/var";
      fsType = "zfs";
    };

  fileSystems."/var/log" =
    { device = "nvme/rpool/rootfs/var/log";
      fsType = "zfs";
    };

  fileSystems."/var/lib" =
    { device = "nvme/rpool/rootfs/var/lib";
      fsType = "zfs";
    };

  fileSystems."/var/lib/docker" =
    { device = "nvme/rpool/rootfs/var/lib/docker";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/56F8-CBAD";
      fsType = "vfat";
    };

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
